---

- name: 
  hosts: local
  become: true
  vars_files:
    - ../vars/user.yml

  tasks:
  - name: update all packages
    become: yes
    apt:
      upgrade: dist
      update_cache: yes
      cache_valid_time: 3600

  - name: install apt latest packages
    become: yes
    apt: name={{ item }} state=latest
    loop:
      - npm
      - nodejs
      - sshuttle

  - name: get vscode
    become: yes
    get_url:
      url: https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64
      dest: "/home/{{ user_name }}/Downloads/vscode.deb"

  - name: install vscode
    become: yes
    apt:
      deb: "/home/{{ user_name }}/Downloads/vscode.deb"

  - name: install docker
    become: yes
    apt: name={{ item }} state=latest
    loop:
      - docker-ce
      - docker-ce-cli
      - containerd.io

  - name: get docker-compose
    become: yes
    shell: curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    args:
      warn: no

  - name: apply executable permisions on docker-compose
    become: yes
    file:
      path: /usr/local/bin/docker-compose
      mode: '555'

...