---

- name: 
  hosts: local
  become: true
  vars_files:
    - ../vars/user.yml

  tasks:
  - name: update all packages
    become: yes
    apt:
      upgrade: dist
      update_cache: yes
      cache_valid_time: 3600

  - name: install apt latest packages
    become: yes
    apt: name={{ item }} state=latest
    loop:
      - npm
      - nodejs
      - sshuttle

  - name: get vscode
    become: yes
    get_url:
      url: https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64
      dest: "/home/{{ user_name }}/Downloads/vscode.deb"

  - name: install vscode
    become: yes
    apt:
      deb: "/home/{{ user_name }}/Downloads/vscode.deb"

  - name: ensure docker GPG key
    become: yes
    apt_key:
      url: https://download.docker.com/linux/debian/gpg
      state: present

  - name: ensure docker repository
    become: yes
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/debian stretch stable
      state: present

  - name: index docker repo into cache
    become: yes
    apt:
      update_cache: yes
      name: "*"
      state: present
      force_apt_get: yes
    failed_when: false

  - name: install docker
    become: yes
    package: name={{ item }} state=present
    loop:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose

  - name: apply executable permissions on docker-compose
    become: yes
    file:
      path: /usr/local/bin/docker-compose
      mode: '555'

  - name: check if docker group exists 
    shell: |
      if grep -q docker /etc/group
        then
          echo "yes"
        else
          echo "no"
        fi
    register: docker_group_exists

  - name: create docker group
    become: yes
    shell: groupadd docker
    when : docker_group_exists.stdout == "no"
    args:
      warn: no

  - name: add user_name to docker group
    become: yes
    shell: usermod -aG docker {{ user_name }}
    args:
      warn: no

  - name: check if sdkman is installed 
    shell: test -d '/home/{{ user_name }}/.sdkman' && echo "yes" || echo "no"
    register: is_sdkman_installed

  - name: install sdkman
    shell: curl -s {{ sdkman_script_install_url }} | bash executable=/bin/bash
    when : is_sdkman_installed.stdout == "no"
    args:
      warn: no

  - name: add sdkman in .bashrc file
    lineinfile: dest={{ user_home_path }}/.bashrc regexp="\/.sdkman/bin\/sdkman\-init\.sh" line='[[ -s "{{ sdkman_folder }}/bin/sdkman-init.sh" && ! $(which sdkman-init.sh) ]] && source "{{ sdkman_folder }}/bin/sdkman-init.sh"'

  - name: install java with sdkman
    shell: source {{ sdkman_folder }}/bin/sdkman-init.sh && sdk install java 8.0.292-open
    args:
      executable: /bin/bash

  - name: install gradle with sdkman
    shell: source {{ sdkman_folder }}/bin/sdkman-init.sh && sdk install gradle
    args:
      executable: /bin/bash
...