---

- name: 
  hosts: local
  become: true
  vars_files:
    - ../vars/shield.yml

  tasks:
  - name: Update all packages
    become: yes
    apt:
      upgrade: dist
      update_cache: yes
      cache_valid_time: 3600

  - name: install apt latest packages
    become: yes
    apt: name={{ item }} state=latest
    loop: [ 'git', 'npm', 'nodejs', 'sshuttle' ]

  - name: install snap classic packages
    become: yes
    snap: name={{ item }} classic=yes
    loop: [ 'intellij-idea-community', 'datagrip', 'slack', 'code' ]

  - name: install docker
    become: yes
    apt: name={{ item }} state=latest
    loop: [ 'docker-ce', 'docker-ce-cli', 'containerd.io' ]

  - name: install teams
    become: yes
    snap:
      name: teams

...